extends PanelContainer

onready var richTextLabel = get_node("Panel/RichTextLabel")

func _ready():
	richTextLabel.add_text("Game idea by Pete Goodwin, created for Game Off 2017")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Font: http://www.1001fonts.com/sf-atarian-system-font.html")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Alien ships")
	richTextLabel.newline()
	richTextLabel.add_text("This work has been released under the Creative Commons BY License: https://creativecommons.org/licenses/by/4.0/")
	richTextLabel.newline()
	richTextLabel.add_text("By MillionthVector (http://millionthvector.blogspot.de)")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Engine sound by Pete Goodwin")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Other sounds by the following user: LittleRobotSoundFactory ")
	richTextLabel.newline()
	richTextLabel.add_text("( https://freesound.org/people/LittleRobotSoundFactory/ )")
	richTextLabel.newline()
	richTextLabel.add_text("sounds taken from https://freesound.org/people/LittleRobotSoundFactory/packs/16689/" )
	richTextLabel.newline()
	richTextLabel.add_text("Licence: http://creativecommons.org/licenses/by/3.0/")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Explosion by tommccann (https://freesound.org/people/tommccann/)")
	richTextLabel.newline()
	richTextLabel.add_text("Licence: http://creativecommons.org/publicdomain/zero/1.0/")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Jump sound by Taira Komori http://taira-komori.jpn.org/freesounden.html")
	richTextLabel.newline()
	richTextLabel.add_text("Licence: http://creativecommons.org/licenses/by/3.0/")
	richTextLabel.newline()
	richTextLabel.newline()
	richTextLabel.add_text("Stars and Rocks created in Filter Forge 6.0")

func _onBackButton():
	get_tree().change_scene("res://scenes/welcome.tscn")
